---
- include_tasks:                '../tasks/template_files.yml'
  vars:
    source_suite:               "{{ os_release_name }}"
    template_files:
      - owner:                  'root'
        group:                  'root'
        mode:                   '0644'
        src:                    'templates/conf/sources.list.d/list.j2'
        dest:                   "/etc/apt/sources.list.d/debian_{{ source_suite }}.list"

- assert:
    that:               True
    quiet:              True
  changed_when:         True
  when:                 template_files_result.changed
  notify:               'run updates'


- include_tasks:                '../tasks/template_files.yml'
  vars:
    source_suite:               "{{ os_release_name }}-updates"
    template_files:
      - owner:                  'root'
        group:                  'root'
        mode:                   '0644'
        src:                    'templates/conf/sources.list.d/list.j2'
        dest:                   "/etc/apt/sources.list.d/debian_{{ source_suite }}.list"

- assert:
    that:               True
    quiet:              True
  changed_when:         True
  when:                 template_files_result.changed
  notify:               'run updates'

- include_tasks:                '../tasks/template_files.yml'
  vars:
    source_suite:               "{{ os_release_name }}-backports"
    template_files:
      - owner:                  'root'
        group:                  'root'
        mode:                   '0644'
        src:                    'templates/conf/sources.list.d/list.j2'
        dest:                   "/etc/apt/sources.list.d/debian_{{ source_suite }}.list"

- assert:
    that:               True
    quiet:              True
  changed_when:         True
  when:                 template_files_result.changed
  notify:               'run updates'
